[package]
name = "neural-digits"
version = "0.1.0"
authors = ["omicronns <omicronns@gmail.com>"]

[dependencies]
nalgebra = { version = "*", features = ["serde-serialize"] }
flate2 = "*"
byteorder = "*"
bincode = "*"
serde = "*"
serde_derive = "*"
